<?xml version="1.0" ?>
<robot name="amr_ust" xmlns:xacro="http://www.ros.org/wiki/xacro">


<xacro:include filename="$(find mecanum_bot_description)/urdf/materials.xacro" />
<xacro:include filename="$(find mecanum_bot_description)/urdf/amr_ust_gen.gazebo" />

<xacro:arg name="param_file_path" default="$(find mecanum_bot_description)/bot_config/mecanum_bot_params.yaml" />
<xacro:property name="params_file" value="$(arg param_file_path)"/>
<xacro:property name="bp" value="${xacro.load_yaml(params_file)}"/>

<xacro:property name="mass" value="${bp['bot_mass']}"/>
<xacro:property name="ixx" value="${bp['bot_ixx']}"/>
<xacro:property name="iyy" value="${bp['bot_iyy']}"/>
<xacro:property name="izz" value="${bp['bot_izz']}"/>
<xacro:property name="length" value="${bp['chassis_length']}"/>
<xacro:property name="width" value="${bp['chassis_width']}"/>
<xacro:property name="height" value="${bp['chassis_height']}"/>
<xacro:property name="grd_height" value="${bp['chassis_grd_height']}"/>

<xacro:property name="wheel_mass" value="${bp['wheel_mass']}"/>
<xacro:property name="wheel_ixx" value="${bp['wheel_inertia'][0]}"/>
<xacro:property name="wheel_iyy" value="${bp['wheel_inertia'][1]}"/>
<xacro:property name="wheel_izz" value="${bp['wheel_inertia'][2]}"/>
<xacro:property name="wheel_ixy" value="${bp['wheel_inertia'][3]}"/>
<xacro:property name="wheel_ixz" value="${bp['wheel_inertia'][4]}"/>
<xacro:property name="wheel_iyx" value="${bp['wheel_inertia'][5]}"/>
<xacro:property name="wheel_iyz" value="${bp['wheel_inertia'][6]}"/>
<xacro:property name="wheel_izx" value="${bp['wheel_inertia'][7]}"/>
<xacro:property name="wheel_izy" value="${bp['wheel_inertia'][8]}"/>

<xacro:property name="wheel_dia" value="${bp['wheel_diameter']}"/>
<xacro:property name="wheel_thickness" value="${bp['wheel_thickness']}"/>
<xacro:property name="wtw_l" value="${bp['wheel_to_wheel_length']}"/>
<xacro:property name="wtw_w" value="${bp['wheel_to_wheel_width']}"/>
<xacro:property name="wheel_offZ" value="${bp['wheel_offsetZ']}"/>

<link name="base_footprint"/>
<link name="base_link">
  <inertial>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
    <mass value="${mass}"/>
    <inertia ixx="${ixx}" iyy="${iyy}" izz="${izz}" ixy="0.0" iyz="0.0" ixz="0.0"/>
  </inertial>
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <!-- <mesh filename="file://$(find mecanum_bot_description)/meshes/base_link.stl" scale="0.001 0.001 0.001"/> -->
      <box size="${length} ${width} ${height}" />
    </geometry>
    <material name="silver"/>
  </visual>
  <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <!-- <mesh filename="file://$(find mecanum_bot_description)/meshes/base_link.stl" scale="0.001 0.001 0.001"/> -->
      <box size="${length} ${width} ${height}"/>
    </geometry>
  </collision>
</link>

<link name="wheel_hub_1">
  <inertial>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
    <mass value="${wheel_mass}"/>
    <inertia ixx="${wheel_ixx}" iyy="${wheel_iyy}" izz="${wheel_izz}" ixy="${wheel_ixy}" iyz="${wheel_iyz}" ixz="${wheel_ixz}"/>
  </inertial>
  <visual>
    <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    <geometry>
      <!-- <mesh filename="file://$(find mecanum_bot_description)/meshes/wheel_hub_1.stl" scale="0.001 0.001 0.001"/> -->
      <cylinder radius="${wheel_dia/2}"  length="${wheel_thickness}"/>
    </geometry>
    <material name="silver"/>
  </visual>
  <collision>
    <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    <geometry>
      <!-- <mesh filename="file://$(find mecanum_bot_description)/meshes/wheel_hub_1.stl" scale="0.001 0.001 0.001"/> -->
      <cylinder radius="${wheel_dia/2}"  length="${wheel_thickness}"/>
    </geometry>
  </collision> 
</link>

<link name="wheel_hub_2_1">
  <inertial>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
    <mass value="${wheel_mass}"/>
    <inertia ixx="${wheel_ixx}" iyy="${wheel_iyy}" izz="${wheel_izz}" ixy="${wheel_ixy}" iyz="${wheel_iyz}" ixz="${wheel_ixz}"/>
  </inertial>
  <visual>
    <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0 0"/>
    <geometry>
      <!-- <mesh filename="file://$(find mecanum_bot_description)/meshes/wheel_hub_2_1.stl" scale="0.001 0.001 0.001"/> -->
      <cylinder radius="${wheel_dia/2}"  length="${wheel_thickness}"/>
    </geometry>
    <material name="silver"/>
  </visual>
  <collision>
    <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    <geometry>
      <!-- <mesh filename="file://$(find mecanum_bot_description)/meshes/wheel_hub_2_1.stl" scale="0.001 0.001 0.001"/> -->
      <cylinder radius="${wheel_dia/2}"  length="${wheel_thickness}"/>
    </geometry>
  </collision>
</link>

<link name="wheel_hub_3_1">
  <inertial>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
    <mass value="${wheel_mass}"/>
    <inertia ixx="${wheel_ixx}" iyy="${wheel_iyy}" izz="${wheel_izz}" ixy="${wheel_ixy}" iyz="${wheel_iyz}" ixz="${wheel_ixz}"/>
  </inertial>
  <visual>
    <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    <geometry>
      <!-- <mesh filename="file://$(find mecanum_bot_description)/meshes/wheel_hub_3_1.stl" scale="0.001 0.001 0.001"/> -->
      <cylinder radius="${wheel_dia/2}"  length="${wheel_thickness}"/>
    </geometry>
    <material name="silver"/>
  </visual>
  <collision>
    <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    <geometry>
      <!-- <mesh filename="file://$(find mecanum_bot_description)/meshes/wheel_hub_3_1.stl" scale="0.001 0.001 0.001"/> -->
      <cylinder radius="${wheel_dia/2}"  length="${wheel_thickness}"/>
    </geometry>
  </collision>
</link>

<link name="wheel_hub_4_1">
  <inertial>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
    <mass value="${wheel_mass}"/>
    <inertia ixx="${wheel_ixx}" iyy="${wheel_iyy}" izz="${wheel_izz}" ixy="${wheel_ixy}" iyz="${wheel_iyz}" ixz="${wheel_ixz}"/>
  </inertial>
  <visual>
    <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0 0"/>
    <geometry>
      <!-- <mesh filename="file://$(find mecanum_bot_description)/meshes/wheel_hub_4_1.stl" scale="0.001 0.001 0.001"/> -->
      <cylinder radius="${wheel_dia/2}"  length="${wheel_thickness}"/>
    </geometry>
    <material name="silver"/>
  </visual>
  <collision>
    <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0 0"/>
    <geometry>
      <!-- <mesh filename="file://$(find mecanum_bot_description)/meshes/wheel_hub_4_1.stl" scale="0.001 0.001 0.001"/> -->
      <cylinder radius="${wheel_dia/2}"  length="${wheel_thickness}"/>
    </geometry>
  </collision>
</link>

<link name="imu_link" />

<link name="camera_link">
  <inertial>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
    <mass value="0.378261563112952"/>
    <inertia ixx="7.7e-05" iyy="9.5e-05" izz="9.3e-05" ixy="0.0" iyz="0.0" ixz="0.0"/>
  </inertial>
  <visual>
    <origin xyz="${-(length*0.6)} 0 ${-(height*0.45)}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="file://$(find mecanum_bot_description)/meshes/Camera_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="silver"/>
  </visual>
  <collision>
    <origin xyz="${-(length*0.6)} 0 ${-(height*0.45)}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="file://$(find mecanum_bot_description)/meshes/Camera_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
</link>

<link name="lidar_link">
  <inertial>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
    <mass value="1.5656994294737245"/>
    <inertia ixx="0.000799" iyy="0.000843" izz="0.001052" ixy="0.0" iyz="0.0" ixz="0.0"/>
  </inertial>
  <visual>
    <origin xyz="0.0 0.0 ${-(height*0.9)}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="file://$(find mecanum_bot_description)/meshes/Intel_Realsense_RPLIDAR_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="silver"/>
  </visual>
  <collision>
    <origin xyz="0.0 0.0 ${-(height*0.9)}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="file://$(find mecanum_bot_description)/meshes/Intel_Realsense_RPLIDAR_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
</link>


<joint name="fixed" type="fixed">
  <origin xyz="0.0 0.0 ${grd_height-height}" rpy="0.0 0.0 0.0"/>
  <parent link="base_footprint" />
  <child link="base_link" />
</joint>

<joint name="Revolute 1" type="continuous">
  <origin xyz="${(wtw_l/2)-(wheel_dia/2)} ${width/2 + ((wtw_w/2)-(width/2)- (wheel_thickness/2))} ${-wheel_dia/2}" rpy="0 0 0"/>
  <parent link="base_link"/>
  <child link="wheel_hub_1"/>
  <axis xyz="0.0 1.0 0.0"/>
</joint>

<joint name="Revolute 2" type="continuous">
  <origin xyz="${(wtw_l/2)-(wheel_dia/2)} ${-(width/2 + ((wtw_w/2)-(width/2)- (wheel_thickness/2)))} ${-wheel_dia/2}" rpy="0 0 0"/>
  <parent link="base_link"/>
  <child link="wheel_hub_2_1"/>
  <axis xyz="0.0 1.0 0.0"/>
</joint>

<joint name="Revolute 3" type="continuous">
  <origin xyz="${-((wtw_l/2)-(wheel_dia/2))} ${width/2 + ((wtw_w/2)-(width/2)- (wheel_thickness/2))} ${-wheel_dia/2}" rpy="0 0 0"/>
  <parent link="base_link"/>
  <child link="wheel_hub_3_1"/>
  <axis xyz="-0.0 1.0 0.0"/>
</joint>

<joint name="Revolute 4" type="continuous">
  <origin xyz="${-((wtw_l/2)-(wheel_dia/2))} ${-(width/2 + ((wtw_w/2)-(width/2)- (wheel_thickness/2)))} ${-wheel_dia/2}" rpy="0 0 0"/>
  <parent link="base_link"/>
  <child link="wheel_hub_4_1"/>
  <axis xyz="0.0 1.0 0.0"/>
</joint>


<joint name="Rigid 37" type="fixed">
  <origin xyz="0.0 0.0 ${grd_height-height}" rpy="0 0 0"/>
  <parent link="base_link"/>
  <child link="imu_link"/>
</joint>

<joint name="Rigid 40" type="fixed">
  <origin xyz="${length*0.52} 0.0 ${height/4}" rpy="0 0 0"/>
  <parent link="base_link"/>
  <child link="camera_link"/>
</joint>

<joint name="Rigid 42" type="fixed">
  <origin xyz="0 0 ${(grd_height-height)+(height/2)+0.01}" rpy="0 0 0"/>
  <parent link="base_link"/>
  <child link="lidar_link"/>
</joint>

</robot>
