scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: box_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_laser # need to check frame name 
        max_x: 12.0
        max_y: 12.0
        max_z: 0.5
        min_x: 0.0
        min_y: -12.0
        min_z: -0.5
        
        invert: true # activate to remove all points outside of the box